### ISSUE TITLE
Incorrect "view required params" error

### ISSUE THREAD

**Issue by TrueXakeP** [nvlad/yii2support#10]
The error happens when a property of an object accessed via string's complex syntax. Actually regardless of where the object is taken. And a parameter with an empty name is proposed.

![error](https://cloud.githubusercontent.com/assets/5345528/22415864/30414394-e6d3-11e6-9895-d2511198f6e5.png)
![error](https://cloud.githubusercontent.com/assets/5345528/22416493/85d907d4-e6d7-11e6-9772-b8d5ae3a9a96.png)
```php
<?php

namespace frontend\controllers;

class TestController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
}
```
```php
<?php

/* @var $this yii\web\View */

$t = Yii::$app;

echo "{$t->uniqueId}";
```

**Comment by nvlad** [comment]
Thanks for report.

Please, update plugin to latest version.

**Comment by TrueXakeP** [comment]
Yes it's fixed. Thank you.
