### ISSUE TITLE
Condition parameters does not conform to the condition

### ISSUE THREAD

**Issue by MKiselev** [nvlad/yii2support#105]
![](https://snag.gy/fJdkcb.jpg)

Если написать с двоеточиями, то не ругается.

И с двоеточием и без - оба варианта правильные.

**Comment by insperedia** [comment]
Да, думал об этом когда делал.
На мой взгляд тут надо сделать настройки плагина, так как есть ещё Auto complete.

**Comment by Renkas** [comment]
I'm getting the same false error on 0.4.30.4

![untitled](https://cloud.githubusercontent.com/assets/5357180/26753405/124bfec2-486e-11e7-83cc-fcd968ad54d3.png)
