### ISSUE TITLE
Rename view file

### ISSUE THREAD

**Issue by MuratYMT** [nvlad/yii2support#11]
if use `render('../profile/sidebar')` and rename file 'sidebar.php' e.g. to  '_sidebar.php', in code is replaced `render('../profile/sidebar')` as `render('_sidebar.php')`.
Must be `render('..profile/_sidebar')`

**Comment by nvlad** [comment]
Thanks for reporting!

**Comment by nvlad** [comment]
Fixed, update to latest plugin version
