### ISSUE TITLE
Autocompletion in ActiveRecord class phpdoc for @property

### ISSUE THREAD

**Issue by naffiq** [nvlad/yii2support#112]
Hi!
First of all thanks for the great extension!

I have a little suggestion for autocompleting ActiveRecord's phpdoc blocks from database, `@property` to be more specific.

**Here's sample case:**

You have an ActiveRecord class which already works fine:
```php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "Sample".
 *
 * @property integer $id
 * @property string $title
 * @property integer $user_id
 *
 * @property Users $user
 */
class Sample extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sample';
    }
}
```

Then you need to add a column, named `status_id` via migration.
```
$ php yii migrate/create add_status_id_column_to_sample_table --fields="status_id:integer:notNull:defaultValue(0)"
```

And after that when you are adding new `@property` block, it automatically suggests you columns from `Sample::tableName()` table, which are not currently in PHPDoc block.

I know, that this example is very specific, but I have many projects, where my colleagues weren't adding `@property` tags and the maintenance turns into pain in the ass.

If it's too hard then don't mind this issue 👍

**Comment by insperedia** [comment]
At the current stage plugin will underline PhpDoc for ActiveRecord if @properties do not correspond columns.
Following conditions must be met:
- There should be connection to database in IDE
- Plugin should be able to detect table. If not it will show underline (error) under class keyword. Prefixes currently not supported, but it should be implemented in future.
- There should be any kind of PhpDoc before ActiveRecord class
