### ISSUE TITLE
Support for model rules() autocomplete

### ISSUE THREAD

**Issue by krukru** [nvlad/yii2support#113]
It would be great if we could get autocomplete support for model rules() method.

For example, since the first element in the array is the models attribute that the rule applies on, the autocomplete would display all public attributes of the model. The second rules array value is the validator (required/safe/boolean/etc), so autocomplete would show all the available validator rules.

Then it gets tricky because some validators can have extra parameters, so the plugin would also have to validate this as well.

I will try to help as much as I can with a PR, but I never created a plugin for phpstorm before.

This could be related to https://github.com/nvlad/yii2support/issues/92 however it's in russian and therefore useless for the rest of the community.

**Comment by insperedia** [comment]
Yes, Thanks

**Comment by insperedia** [comment]
I have began work on that

**Comment by insperedia** [comment]
Functionality has been implemeted. Scheduled for next release.

**Comment by insperedia** [comment]
https://plugins.jetbrains.com/plugin/download?updateId=35899
