### ISSUE TITLE
Improve condition parameters inspection

### ISSUE THREAD

**Issue by andrey-yantsen** [nvlad/yii2support#114]
I have 2 completely correct blocks of code, where parameters will be defined later, but the inspection reports errors:
```php
        $query = (new Query())
            ->select('id')
            ->from('translate_source2')
            ->where('message = :msg AND (category = :category OR category LIKE CONCAT(:category, "/%"))');
```
```php
        $updateStmt = Yii::$app->db->createCommand('
            INSERT INTO translate_message2 (id, language, translation)
            VALUES (:id, :lang, :msg)
            ON DUPLICATE KEY UPDATE translation = VALUES(translation)
        ');
```

Parameters are not required to be defined in same command, unless it ends with `query()` or something similar.

**Comment by insperedia** [comment]
They are not required right away, but they required and if you forget it, exception arise. So it was intentional. Right away I do not see scenario where you unable to put parameters values where inspection wants it. If you have such scenario I am ready to discuss it.
