### ISSUE TITLE
Plugin shows error for not Yii objects

### ISSUE THREAD

**Issue by yujin1st** [nvlad/yii2support#115]
![2017-05-03 9 32 52](https://cloud.githubusercontent.com/assets/2317913/25644782/a3e38e98-2fe3-11e7-9cb9-7ecec4ab668c.png)

**Comment by alexantr** [comment]
Have same problem
![phpstorm64_2017-06-13_14-58-15](https://user-images.githubusercontent.com/4941848/27081399-ddb0520c-5048-11e7-9939-db74bcc88c88.png)

**Comment by insperedia** [comment]
Fixed. Will be availible in next release.
