### ISSUE TITLE
Plugin cant find my tables.

### ISSUE THREAD

**Issue by Ni-san** [nvlad/yii2support#117]
Plugin cant find my tables.

The keyword "class" of the AR model underlined with message `Table "public"."mytablename" not found in database connections` for all tables.

I use several local and remote connections (PostgreSQL, if it matters). All databases has same structure. All schemas are loaded into IDE.

Anticipating the question: there are no prefixes.

```
public static function tableName()
{
    return 'public.mytablename';
}
```

Plugin version: 0.4.30.4
PhpStorm 2017.1.2

**Comment by insperedia** [comment]
Thanks. Will implement sachems soon.

**Comment by OndrejVasicek** [comment]
Does it mean, that the plugin can't find any table in Postgre? Because I get the same error, but my table is without the "public." schema. Just "user" for example, but the table exist and the connection is defined.

**Comment by Ni-san** [comment]
@OndrejVasicek , As far as I know, you can't create table without schema in PostgreSQL. You can use default schema:
```
psql (9.5.7)
Type "help" for help.

dbname=# DROP SCHEMA public;
DROP SCHEMA
dbname=# CREATE TABLE test (id serial not null);
ERROR:  no schema has been selected to create in
LINE 1: CREATE TABLE test (id serial not null);
                     ^
dbname=# CREATE SCHEMA public;
CREATE SCHEMA
dbname=# CREATE TABLE test (id serial not null);
CREATE TABLE
dbname=# 
```

**Comment by OndrejVasicek** [comment]
I ment I don't use the `'schema'` keyword in my `tableName()` method.

**Comment by insperedia** [comment]
Postgres support is implemented in the last release.

**Comment by OndrejVasicek** [comment]
Thank you @insperedia .
Also for others, who are still fighting whit this - don't forget to refresh your tables in "database" window in PHPStorm. I had there only few tables, even there should be a lot more of them. I don't know why PHP Storm doesn't refresh db schema at all automatically.
