### ISSUE TITLE
Подсказка типа для Yii::createObject

### ISSUE THREAD

**Issue by tekord** [nvlad/yii2support#119]
Есть классы, реализующие бизнес-логику и создающиеся через Yii::createObject. Этот метод умеет внедрять зависимости, которые активно используются в классах с бизнес-логикой. Вот пример кода инстанцирования и использования класса:

```php
	/** @var SetTaskAssigneeCommand $command */
	$command = Yii::createObject(SetTaskAssigneeCommand::class);
	$command->execute($task, $task->project->tester_id);
```

Приходится писать длинные type hint'ы, т.к. IDE ждёт от createObject результат типа object.

**Вопрос**: возможно ли сделать так, чтобы плагин Yii 2 сообщал IDE тип возвращаемого значения на основе параметра метода Yii::createObject? Тогда можно будет избавиться от надоедливых type hint'ов.

**Comment by insperedia** [comment]
Мы обсуждали этот вопрос с соавтором. Пока мы не нашли, как подобный функционал можно реализовать, и вообще нужно ли. Мы пришли к решению - генерировать PhpDoc с помощью QuickFix. Я реализую данный функционал в ближ недели для данного случая.

**Comment by tekord** [comment]
С SDK платформы не особо знаком, но мне видится это так. Если обнаружен вызов Yii::createObject, то взять тип выражения первого аргумента, если array, то взять оттуда значение class, если string (имя класса), то взять его. Получить ссылку на выражение слева (присвоение) и назначить ему тип на основе аргумента. SDK наверняка должен позволять назначать тип переменной как это делает PhpDoc. Как-то так.

**Comment by insperedia** [comment]
:)

**Comment by tekord** [comment]
@insperedia так это реально? :)

P.S. А есть ли где-то туториалы по SDK платформы или видео лекции помимо официальных доков? Хочется самому попробовать что-нибудь написать.

**Comment by nvlad** [comment]
@tekord как-то это работает - значит реально)

По поводу доков - толковой и полной документации найти не получилось, основные источники это [исходники платформы](https://github.com/JetBrains/intellij-community), [плагинов](https://github.com/JetBrains/intellij-plugins) на [гитхабе попадаются толковые исходники](https://github.com/search?q=topic%3Aintellij-plugin&type=Repositories). Можно поискать плагины с открытым кодом в официальном ["репозитории плагинов"](https://plugins.jetbrains.com/idea) и там черпать вдохновение)

**Comment by insperedia** [comment]
Вот в этом и вся проблема, что документации толковой нету. 
Спрошу на форуме.

**Comment by insperedia** [comment]
Дали ответ на форуме, пока не проверял, но разработчик говорит - должно работать. сейчас очень много работы. Реализую через пару недель.

**Comment by insperedia** [comment]
Вот рабочий вариант. 
Создать файл .phpstorm.meta.php в корне проекта
и написать туда:
`<?php

namespace PHPSTORM_META {

    $STATIC_METHOD_TYPES = [
        \Yii::createObject() => [
            '' == '@',
        ]
    ];
}`

Autocomplete заработает

**Comment by tekord** [comment]
@insperedia ничего себе! Вот это круто, спасибо :)

**Comment by insperedia** [comment]
New plugin provide to IntelliJ type of Yii::createObject call. All cases are supported. New feature will come in next release.

**Comment by insperedia** [comment]
Beta release: https://plugins.jetbrains.com/plugin/download?updateId=35899
