### ISSUE TITLE
Incorrect behaviour for missing view file inspection

### ISSUE THREAD

**Issue by alexxxst** [nvlad/yii2support#12]
I have something like

`$this->render('@app/views/layouts/json', ...);`

PhpStorm plugin says that 
> View file for "@app/views/layouts/json" not found.

So, Yii2 documentation says that view [can be specified in various formats](https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php#L343).

**Comment by nvlad** [comment]
Please describe scenario of using this alias.

in new version add "@" & "//" to ignore for this inspection, and will think on implementing this alias in later versions of the plugin

**Comment by juanmacias** [comment]
Not solved for me... can't detect views from backend environment...

**Comment by nvlad** [comment]
Hi! Please send your
1) IDE name & version
2) Plugin version
3) Project structure contains IDE Project Root, folders with Controller & View files

**Comment by juanmacias** [comment]
1. Phpstorm 2017.3.4
2. Plugin Version: 0.8.38.1
3. The problem is accessing @backend/common/views
<img width="350" alt="screen shot 2018-03-12 at 11 16 39" src="https://user-images.githubusercontent.com/4797797/37278086-dfa090e4-25e6-11e8-8a8e-4caf76f6224f.png">
