### ISSUE TITLE
Missing translation inspection cache bug

### ISSUE THREAD

**Issue by samdark** [nvlad/yii2support#122]
1. Run missing translations inspection on a project A where translation are missing.
2. Switch to project B.
3. Run missing translations inspection on a project B.
4. Issues from project A are reported. Quickfix adds missing translations from totally unrelated project.

**Comment by nvlad** [comment]
This plugin not have this feature, may be inspection from here https://github.com/kalessil/yii2inspections

**Comment by samdark** [comment]
Oh :) Reported it to wrong repo. Sorry.
