### ISSUE TITLE
Inspection "Wrong database parameters" is confused by literal dates

### ISSUE THREAD

**Issue by programaths** [nvlad/yii2support#124]
```php
$db2->createCommand("SELECT ((now() >= '2014-11-10 12:00:00') and (now() <= '2014-11-16 23:59:00'))")->queryScalar()
```

Confuses the inspection **Wrong database parameters** and requires that an associative array like :
```php
[':59'=>0,':00'=>0]
```

Is given as a second parameters.

Context should be taken into account when parameters are checked. (i.e. Ignoring everything between quotes.).

**Comment by programaths** [comment]
A pull request is available : https://github.com/nvlad/yii2support/pull/125

**Comment by insperedia** [comment]
Merged
