### ISSUE TITLE
type provider API contract violation

### ISSUE THREAD

**Issue by neuro159** [nvlad/yii2support#129]
index access (==any resolve except explicit resolveLocal which is not useful) is NOT allowed from getType!
if such exception is not fixed plugin may get blacklisted
please reach me if you need assistance on how to approach this properly

> Error while indexing /home/b0t/PhpstormProjects/opencity/modules/site/models/Dictionary.php
> To reindex this file IDEA has to be restarted
>
> com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
>     at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:730)
>     at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:679)
>     at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:662)
>     at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:346)
>     at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
>     at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
>     at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
>     at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:608)
>     at com.jetbrains.php.PhpIndexImpl.getInterfacesByName(PhpIndexImpl.java:285)
>     at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveGlobal(ClassReferenceImpl.java:115)
>     at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveGlobal(ClassReferenceImpl.java:69)
>     at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:145)
>     at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:142)
>     at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
>     at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
>     at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
>     at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
>     at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
>     at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:137)
>     at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:123)
>     at com.nvlad.yii2support.typeprovider.ActiveRecordTypeProvider.findClassByMethodReference(ActiveRecordTypeProvider.java:68)
>     at com.nvlad.yii2support.typeprovider.ActiveRecordTypeProvider.getType(ActiveRecordTypeProvider.java:41)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:57)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:39)
>     at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:56)
>     at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
>     at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:39)
>     at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getType(PhpReferenceImpl.java:212)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpType.add(PhpType.java:152)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeAnalyserVisitor.addType(PhpTypeAnalyserVisitor.java:55)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeAnalyserVisitor.visitPhpAssignmentExpression(PhpTypeAnalyserVisitor.java:165)
>     at com.jetbrains.php.lang.psi.elements.impl.AssignmentExpressionImpl.accept(AssignmentExpressionImpl.java:37)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:46)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:39)
>     at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:56)
>     at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
>     at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:39)
>     at com.jetbrains.php.lang.psi.elements.impl.PhpTypedElementImpl.getType(PhpTypedElementImpl.java:26)
>     at com.jetbrains.php.lang.psi.elements.impl.PhpExpressionImpl.getType(PhpExpressionImpl.java:59)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeAnalyserVisitor.visitPhpField(PhpTypeAnalyserVisitor.java:401)
>     at com.jetbrains.php.lang.psi.elements.impl.FieldImpl.accept(FieldImpl.java:49)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:46)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:39)
>     at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:56)
>     at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
>     at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
>     at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:39)
>     at com.jetbrains.php.lang.psi.stubs.PhpFieldElementType.createStub(PhpFieldElementType.java:35)
>     at com.jetbrains.php.lang.psi.stubs.PhpFieldElementType.createStub(PhpFieldElementType.java:20)
>     at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.createStub(DefaultStubBuilder.java:113)
>     at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:88)
>     at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:83)
>     at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:58)
>     at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:39)
>     at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
>     at com.intellij.psi.stubs.StubUpdatingIndex$3.lambda$map$0(StubUpdatingIndex.java:212)
>     at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:934)
>     at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:211)
>     at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:194)
>     at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272)
>     at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
>     at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215)
>     at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1615)
>     at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$18(FileBasedIndexImpl.java:1551)
>     at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
>     at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1510)
>     at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498)
>     at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:105)
>     at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:229)
>     at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
>     at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:246)
>

**Comment by insperedia** [comment]
Yes, it felt wrong to access  index in such performance critical method, next time will post on forum a question first.
I published version where this functionality is disabled.
Cases that solves wrong code was:
`$address = Address::find()->one();`
In framework one() method returns generic ActiveRecord but disabled module made IDE to know that $address has type Address. 
So as I understand there no simple solution to implement this?

**Comment by insperedia** [comment]
Hm, got an idea just to analyse PsiElement tree to get needed class name.

**Comment by insperedia** [comment]
Is it allowed to use methodReference.getClassReference() in getType method? 
Or better just to iterate throught PsiElement tree?

**Comment by insperedia** [comment]
Yes, it felt wrong to access index in such performance critical method, next time will post a questionon forum first.
I published version where this functionality is disabled.
I was tring to solve this case:
$address = Address::find()->one();
In framework one() method returns generic ActiveRecord but disabled module made IDE to know that $address has type Address.
**So I have two groups of questions:**
1.  How convert ClassReference to actual class without resolve? May be it is possible to instantiate PhpClass object from my code?
2.  Is it ok to call methodReference.getClassReference() in getType() method ? 
Or it is better to use PsiElement tree to find needed info? In theory I can get first child of parent PsiElement (whole expression) to get class name?

**Comment by neuro159** [comment]
return a custom signature key (and params as required) and do lookups/future work in the "getBySignature"

**Comment by insperedia** [comment]
fixed
