### ISSUE TITLE
Support navigating to a view specified using "//path/to/view" syntax

### ISSUE THREAD

**Issue by gvlasov** [nvlad/yii2support#133]
http://www.yiiframework.com/doc-2.0/guide-structure-views.html#named-views

```php
// In controller
return $this->render("//path/to/view");
```

When I use "Navigate to declaration" action in Idea with the cursor on the view name in this case, nothing happens. I would like it to open the file in editor.

**Comment by rezets19** [comment]
+1

**Comment by rsmike** [comment]
+1. Could be extremely useful for those who use same views/snippets in different views - it's a very common case
