### ISSUE TITLE
Can support tablePrefix from the config file?

### ISSUE THREAD

**Issue by zhang988925** [nvlad/yii2support#135]
Can support tablePrefix from the config file?
My IDE tip 'not found in database connections', Because I configured tablePrefix.
I see the DatabaseUtils.getTableByActiveRecordClass() method without judgment.

**Comment by zhang988925** [comment]
I found that the configuration  view->theme  is also not recognized. 
I want to improve this plugin, but I found the source code is not up to date. How can I get the latest source code?
 Thanks very much

**Comment by insperedia** [comment]
tablePrefix is planned as next feature, and I expect to make it very soon. I will implement it with plugin settings. So do not hassle with this, I ll try to deliver it asap.

**Comment by insperedia** [comment]
I pushed last sources in master, now it may work :), if you want to make some improvments you are welcome. Regarding tablePrefix, I will implement it my self.

**Comment by insperedia** [comment]
In testing right now. Will rollout update next week.

**Comment by zhang988925** [comment]
Thank you very much for sharing. This plugin saves me a lot of time

**Comment by insperedia** [comment]
yii2support plugin with tablePrefix support is availible  here: https://plugins.jetbrains.com/plugin/download?updateId=39083
