### ISSUE TITLE
Feature request: Attribute autocomplete for ActiveForm::Field method

### ISSUE THREAD

**Issue by dotterian** [nvlad/yii2support#137]
Default method for outputting ActiveForm fields in Yii2 is
```php
$form->field($model, 'attrbuteName')->textInput();
```
Most of times I struggle to remember what were the attributes for this particular model and autocomplete could save my time more than once.
Seeing how autcomplete for `$form->field(...)->widget()` options part was implemented makes me guess why `field()` method wasn't.

**Comment by insperedia** [comment]
Thanks. I my self always remember attributes, now will put this problem more priority. Will implement it after upcoming fix what in testing now.
