### ISSUE TITLE
Doc block of the variables passed to a view

### ISSUE THREAD

**Issue by mike-kramer** [nvlad/yii2support#138]
Can you automatically add a doc-block of variables, passed to a view file? I mean, in controller I write
```php
return $this->render("viewName", ["a" => 2, "b" => "some value"]);
```
and your plugin writes in view automatically:
```php
/* @var mixed $a */
/* @var mixed $b */
```

**Comment by marqu3s** [comment]
Would like to see this too! With an update doc block action when we add more variables.
