### ISSUE TITLE
Неиспользуемый параметр

### ISSUE THREAD

**Issue by zhukovsergey** [nvlad/yii2support#139]
Если во view поставить пре или постинкремент для переменной, то в в контроллере она вдруг 
 становится "неспользуемой" 
```
<?=$counter++?>
<?=++$counter?>
```

![image](https://user-images.githubusercontent.com/1946769/30686632-109e78a4-9ee3-11e7-99a0-60a3139abc8c.png)

**Comment by nvlad** [comment]
интересное поведение, спасибо!

**Comment by nvlad** [comment]
Исправлено в последнем релизе.
