### ISSUE TITLE
Code completion in configuration arrays

### ISSUE THREAD

**Issue by insperedia** [nvlad/yii2support#14]
I think it would be useful functionality to have code completion in Yii configuration arrays that creates objects.
I have stated to search possibility to make contribution, so if you have not time so probably it will do it.

**Comment by nvlad** [comment]
You write about component configuring array on create 
```php
$model = new User(['username' => ' Example User']);
```
or about the framework configuration?

if first see

**Comment by insperedia** [comment]
I ment first of all YiiBase::createObject method, that is used in particular for building components of application from configuration arrrays.
I think that in first version code completion could be activated when "class" attribute if defenied explicitly.

**Comment by insperedia** [comment]
Could you write an email to contact@insperedia.com . What to ask few small questions.
