### ISSUE TITLE
ActiveRecord can't find corresponding table in 2017.3 EAP

### ISSUE THREAD

**Issue by dotterian** [nvlad/yii2support#140]
On sceenshot below you can see that table exists in database panel but there's error "Table 'user' not found in database connections". It occurs with all models in all Yii2 projects after IDE update.
![screenshot from 2017-10-03 04-07-57](https://user-images.githubusercontent.com/6250486/31105969-77fb132a-a7f0-11e7-941b-9b4b4d5aba2b.png)

**Comment by insperedia** [comment]
Thanks for report. Will take alook

**Comment by tdrpic** [comment]
I'm having the same issue with PhpStorm 2017.2.4, connecting to PostgreSQL

**Comment by insperedia** [comment]
fixed. PHP Storm 2017.3 support + PostgresSQL support
