### ISSUE TITLE
Override the tableName method, the plugin does not correctly define the table

### ISSUE THREAD

**Issue by DAGpro** [nvlad/yii2support#141]
If override the tablename method in a child class, the plugin does not correctly identify the table name
![2017-10-06_17-49-22](https://user-images.githubusercontent.com/9422078/31283942-c6c52046-aabf-11e7-879b-49c7687cde1f.png)

And so work:
![2017-10-06_17-53-35](https://user-images.githubusercontent.com/9422078/31284053-1a5c7ee8-aac0-11e7-9545-33e60bc297de.png)
![2017-10-06_17-59-07](https://user-images.githubusercontent.com/9422078/31284067-224446d6-aac0-11e7-85f7-15a0f0b910ca.png)
![2017-10-06_17-58-03](https://user-images.githubusercontent.com/9422078/31284062-1f9adc42-aac0-11e7-93cc-302cdb0690b8.png)

p.s. google translate

**Comment by nvlad** [comment]
Thx for report! Fixed in today release.
