### ISSUE TITLE
Подсвечивает ошибкой prepare statement в db->createCommand()

### ISSUE THREAD

**Issue by Coolkop** [nvlad/yii2support#146]
```php
 \Yii::$app->db->createCommand('SELECT * FROM table WHERE id = :id AND date < $date)
    ->bindParam(':id', $id)
    ->queryAll();
```
При таком варианте бинда параметров сам SQL подсвечивается ошибкой и предлагает использовать через:
```php
\Yii::$app->db->createCommand('SELECT * FROM table WHERE id = :id AND date < $date, [':id' => $id]);
```

**Comment by insperedia** [comment]
Спасибо за вклад.

**Comment by insperedia** [comment]
Cценарий, где необходима именно эта конструкция, не такой частый, на мой взгляд. Учитывая относительную сложность я поставлю статус "отложено". Если есть аргумент, почему этот функционал выжен, возможна дисскусия.
