### ISSUE TITLE
Create directory for controller views when creating views

### ISSUE THREAD

**Issue by samdark** [nvlad/yii2support#147]
1. Create new controller `TestController`.
2. Type `return $this->render('index');` in `actionIndex()`.
3. Create view via intent.
4. Nothing happens because directory `test` isn't there.

IDE should create directory for me.

**Comment by insperedia** [comment]
Thanks. This is nvlad's area, do not plan to touch it until I finished work with some features (Url and Params autocompletion).  So cannot say when we will implement it.

**Comment by samdark** [comment]
It's not a big deal. Just a small inconvenience.

**Comment by samdark** [comment]
Thank you and @nvlad for working on it.
