### ISSUE TITLE
Suppress exception higlighting in view files somehow?

### ISSUE THREAD

**Issue by robsch** [nvlad/yii2support#153]
With an update of PHPStorm missing exception handling seems to get more highlighted now. This occurres with DetailView, GridView and probably other widgets. What would you suggest how to get rid of that? 

![exception-in-view-file](https://user-images.githubusercontent.com/2900992/34246271-23576a54-e62e-11e7-9adf-7c46cbe66cbf.png)

Thank you and happy holidays!

**Comment by insperedia** [comment]
Alt + Enter with cursor in yellow area - then you can choose if you want to suppress or disable inspection. You can also disable inspection in settings.

**Comment by robsch** [comment]
Thanks. I know that but I thought there might be a more general solution. Suppressing seems to be the better approach though.
