### ISSUE TITLE
IDE Fatal Error (Method com/nvlad/yii2support/database/MissedParamQuickFix.getName()Ljava/lang/String; is abstract)

### ISSUE THREAD

**Issue by sxnazirov** [nvlad/yii2support#162]
How to fix this problem?
![image](https://user-images.githubusercontent.com/9702115/36464429-95b13dd4-16f1-11e8-827b-f068f973cfc0.png)

![image](https://user-images.githubusercontent.com/9702115/36464441-ac2c3f82-16f1-11e8-8047-5abebf380311.png)

**Comment by sxnazirov** [comment]
IDEA info
![image](https://user-images.githubusercontent.com/9702115/36464503-0b92ad1c-16f2-11e8-9357-86e502e614d1.png)

**Comment by nvlad** [comment]
Hi! Please send code example for error reproduce.

**Comment by sxnazirov** [comment]
![image](https://user-images.githubusercontent.com/9702115/36933901-bde06906-1f02-11e8-8a06-6533a19fdfd1.png)
This error happens when I add property in comment.

**Comment by nvlad** [comment]
Hi! Please check on latest plugin Beta version ([download v0.8](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=43770))

https://plugins.jetbrains.com/plugin/9388-yii2-support

**Comment by sxnazirov** [comment]
Thanks alot for your help!
