### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by eniuz** [nvlad/yii2support#163]
Hi guys. It's been a while since I had to disable yii2 support in my phpstorm. I had a look into releases and couldn't find anything new coming recently. Is this plugin actively maintained?

**Comment by nvlad** [comment]
Hi! Yes, now testing [View support v2](https://github.com/nvlad/yii2support/milestone/1?closed=1) and route completion & resolve supports

**Comment by nvlad** [comment]
New version is published
