### ISSUE TITLE
 Некорректная работа с View контроллеров во вложенных папках

### ISSUE THREAD

**Issue by Yannn** [nvlad/yii2support#166]
Если контроллеры лежат не в папке controllers, но и вложенных, например, controllers/admin, то в контроллерах подобных controllers/admin/IndexController не распознается обращение к вьюхе вида $this->render('view'), хотя должно распознаваться как к  views/admin/index/view.php.

И спасибо за крутейший плагин, не мешало бы обзавестись другим способом поддержки (Я.Деньги?) paypal  и биткоин не имеется.

**Comment by nvlad** [comment]
Какую версию плагина используете? И какая версия IDE? 
В недавнем релизе [0.8.38](http://plugins.jetbrains.com/plugin/9388-yii2-support/update/43895) была полностью переработана работа с View.

Спасибо, приятно слышать, что наш проект помогает людям! По поводу добавления других способов поддержки проекта - обязательно займусь на днях)

**Comment by Yannn** [comment]
В том то и дело, что увидел обновление про пути представлений и сразу обновился до 0.8.38.1, но не помогло
![clip_2](https://user-images.githubusercontent.com/3951215/37093512-657ee9c2-2231-11e8-9ec0-859542cf0692.jpg)

**Comment by nvlad** [comment]
можете прислать структуру проекта более развёрнуто? если открыт то ссылку на него, если нет, то дерево проекта, с указанием где расположен контроллер и где расположен вид который не обнаруживается плагином? можно на почту support@nvlad.com

**Comment by Yannn** [comment]
да все просто вроде
![clip_3](https://user-images.githubusercontent.com/3951215/37106328-6131d2ae-2253-11e8-9c7c-99daa06b0e5a.jpg)
![clip_4](https://user-images.githubusercontent.com/3951215/37106330-615d02bc-2253-11e8-813e-9afb548b4412.jpg)

**Comment by nvlad** [comment]
Очень странно. Воспроизвёл структуру файлов, похожую на вашу, view нашёлся и открывается (проверено на PhpStorm 2016.2 и PhpStorm 2017.3)

Предлагаю попробовать следующее:
1) посмотреть ошибки в работе плагина (на скрине нарисовал куда смотреть)
2) сбросить кэш и индексы (File -> Invalidate Caches / Restart...)
3) прислать следующую информацию: ОС, версия IDE, используемый шаблон Yii, версия Yii

![monosnap 2018-03-08 12-16-34](https://user-images.githubusercontent.com/2493052/37144875-681965a0-22d0-11e8-8b2b-66cf5e9cbb41.png)

**Comment by mmkulikov** [comment]
Отличный плагин. Но обновился на 0.8.38.1 и получил аналогичную проблему даже со стандартной структурой папок. Вот скрин [https://yadi.sk/i/vf6pT8pQ3TBrUX](url)

**Comment by mmkulikov** [comment]
![2018-03-09_14-27-46](https://user-images.githubusercontent.com/4347816/37207693-c9b0c3e0-23a6-11e8-8155-186d2b344828.png)

**Comment by mmkulikov** [comment]
Invalidate cache не помогает. А к этому функционалу уже привык-с ((

**Comment by nvlad** [comment]
@mmkulikov первое что бросается в глаза, сайт на yii расположен не в корневой директории проекта. Уже получается не совсем стандартная структура. Где у вас расположены папка vendor? много ли у вас в этом проекте папок сайтами на yii? (таких как папка bwn расположенная в корне проекта).

**Comment by mmkulikov** [comment]
![2018-03-09_15-13-40](https://user-images.githubusercontent.com/4347816/37209080-771123d6-23ac-11e8-874b-5fa4626f6a91.png)

**Comment by mmkulikov** [comment]
Vendor в bwn. В bwn развернут стандартный advanced шаблон YII2

**Comment by mmkulikov** [comment]
![2018-03-09_15-15-34](https://user-images.githubusercontent.com/4347816/37209136-bca7d192-23ac-11e8-915d-43e6f42f647f.png)

**Comment by nvlad** [comment]
никогда так не структурировал проект, обычно все связанные файлы храню в корне проекта в директории /resources расположенной рядом с frontend, backend.

попробуйте прилагаемый билд, должен заработать, а после тестов выпущу в релиз.

[yii2support.jar.zip](https://github.com/nvlad/yii2support/files/1800997/yii2support.jar.zip)

**Comment by mmkulikov** [comment]
> никогда так не структурировал проект,

> Там есть файлы никак не связанные непосредственно с сайтом, но связаны с проектом. Потому вполне логично "опустил" весь сайт в папку. Это ведь структура проекта, а не структура непосредственно на сервере. На сервере будет только "чистый" код, без лишнего мусора. Корень git`a - это у меня не корень проекта, а корень как раз сайта

А по делу. Никогда не ставил плагины с архива. Попробую - отпишусь

**Comment by nvlad** [comment]
Ставите сам архив или файл из архива?

**Comment by mmkulikov** [comment]
Сам архив

**Comment by nvlad** [comment]
Надо файл из архива (.jar), приходится запаковывать, так как github запрещает выкладывать jar

**Comment by mmkulikov** [comment]
Да. Так получилось. Работает.

**Comment by mmkulikov** [comment]
Обновления следующие сам подхватит? Не помешает что я руками ставил?

**Comment by nvlad** [comment]
да, обновления должны нормально приходить.

**Comment by piliugin** [comment]
Аналогичная проблема после обновления на 0.8.38.1, view подчеркиваются красным и при клике никакого перехода.
Сброс кеша не помог, ошибок плагина нет, установка из архива yii2support.jar.zip (yii2support.jar) тоже не решила проблему.
![2018-03-14 10 46 06](https://user-images.githubusercontent.com/9514414/37389329-f1a06a50-2774-11e8-8988-3c51b8b91b9f.png)
![2018-03-14 10 42 03](https://user-images.githubusercontent.com/9514414/37389278-c3c3f854-2774-11e8-9303-186e3e9076b5.png)
![2018-03-14 10 43 19](https://user-images.githubusercontent.com/9514414/37389279-c3e60b10-2774-11e8-993a-d99ef226ba5e.png)

**Comment by nvlad** [comment]
@piliugin перенесите проект на первый уровень вложенности в проекте.

PS: Сколько у вас в проекте Yii проектов?

**Comment by piliugin** [comment]
@nvlad это не совсем правильно с точки зрения структуры проекта. Не хотелось бы мешать исходный код с файлами настройки сборки, окружения, утилит валидации кода и т.д.
Мне кажется, правильнее было бы вынести в настройки плагина опцию для указания корня проекта.

> PS: Сколько у вас в проекте Yii проектов?
один

**Comment by mmkulikov** [comment]
> перенесите проект на первый уровень вложенности в проекте.
Извиняюсь что влезаю. Но почему проект сторма должен быть корнем yii? Это не логично и не удобно. В проекте сторма, например, я храню и другие "нужные" вещи, к примеру всякие доступы, логины, тз и прочую лабуду от заказчика...
Мне кажется что Вы несколько не с той "стороны" подошли к отсчету путей. Сам YII прекрасно как-то справляется с отсчетом от @app

**Comment by mmkulikov** [comment]
![2018-03-14_19-03-15](https://user-images.githubusercontent.com/4347816/37418236-6e66aee2-27ba-11e8-8991-596ab2ffba65.png)
Перестал "подсказывать" (давать на выбор) если вьюха лежит в подпапке

**Comment by nvlad** [comment]
@piliugin отчасти согласен, по этому добавил поиск Yii проектов в папках первого уровня. По поводу настройки пути к Yii проекту - была мысль, но пока не хочу тратить на это время. Да и опять же кто-то убирает корень yii проекта на вторую третью вложенность, кто-то захочет сделать 2-3 yii проекта в одном шторм проекте, ситуация не стандартная и редко встречаемая. Так что пока предлагаю воспользоваться моим предложением или создать проект в папке с yii и открывать его в отдельном окне шторма.

@mmkulikov по мне так всё наоборот логично и удобно, yii проект делаю в шторме, а "логины, доступы, тз и прочую лабуду от заказчика" на гугл диске в папке "работа/заказчик/проект" шторм не поддерживает doc, pdf, xls и прочие форматы в которых обычно присылают информацию заказчики, а вот гугл диск прекрасно с ними справляется.
По поводу точки отсчёта - как-то не встречал ранее подхода используемого вами, и в реализации проще именно так. Опять же Вы писали что .git у вас находится в корне сайта, а не корне проекта... как бы намекает. В Yii корнем папка куда развернули шаблон yii приложения и где расположен .git (что можно изменить, если захотеть), вот и у меня отсчёт от корня проекта, только штормовского.


В общем хочу подвести итог нашего общения:
1) Как хранить проект и сопутсвующие файлы - дело вкуса.
2) Плагин работает сейчас именно так и когда изменится не известно.
3) Могу предложить поучаствовать в развитии проекта и реализовать этот функционал самим, мы будем рады Вашему участию.

**Comment by nvlad** [comment]
@mmkulikov по поводу view при работе с почтой - вынес в отдельное Issue #168 можете подписаться на обновления статуса.

**Comment by mmkulikov** [comment]
![2018-03-15_11-36-04](https://user-images.githubusercontent.com/4347816/37455165-23283168-2845-11e8-9f95-b93ab5854ef7.png)
Вот собственно такая "необычная" вьюха. Вполне реально работает. Но к сожалению в плагине ошибка получается.
Вьюха от контроллера бэкенда (хотя это в принципе должно быть без разницы).

**Comment by mmkulikov** [comment]
> Могу предложить поучаствовать в развитии проекта и реализовать этот функционал самим, мы будем рады Вашему участию.

Я так понимаю, что вся проблема в "поиске" корня YII проекта... Не вижу ничего сложно. Присоединиться - я подумаю над этим предложением, хотя языком для написания как я понимаю является java - не самый мой любимый язык )) но имел возможность и на нём писать.

**Comment by nvlad** [comment]
@mmkulikov костыль в виде поиска уже сделан (по первому уровню вложенности) в версии которую публиковал в этой ветке, но как оказывается его мало. Надо делать какое-то более правильное решение, например настройку с указанием корня проекта (если отбросить возможность добавления нескольких yii проектов в один проект шторма).

Да, разработка ведётся на Java, вроде как можно ещё Kotlin использовать, но пока не пробовали. Java это меньшее из бед, главная беда это плохая документации IntelliJ Plugin API.

**Comment by mmkulikov** [comment]
> если отбросить возможность добавления нескольких yii проектов в один проект шторма

Это уже кощунство :) А по "поиску", может стоит поискать файл YII который в корне yii проекта всегда? Это как вариант...

>  это плохая документации IntelliJ Plugin API.

Это да ))

**Comment by nvlad** [comment]
> Это уже кощунство :)
Мне вот в голову не приходило вкладывать проект в папку :) Так что если мы что-то не делаем, не значит что этого не делает кто-то другой)

> А по "поиску", может стоит поискать файл YII который в корне yii проекта всегда? Это как вариант...

В чистом yii-app-basic четыре `yii` файла :)
![image](https://user-images.githubusercontent.com/2493052/37461518-a04a2b3c-285f-11e8-8152-ad83c497a32a.png)

В принципе подобным образом и делаю только ищу файл `/vendor/yiisoft/yii2/Yii.php`. Поиск по вложенностям крайне извратный получился, да и перебирать весь проект не хочу.

**Comment by mmkulikov** [comment]
> Поиск по вложенностям крайне извратный получился, да и перебирать весь проект не хочу.

Так у сторма же индекс есть. Или он никак не поможет? Никак не воспользоваться его "родным" поиском? Ведь он довольно шустро ищет в проекте файл по Ctrl+Shift+N

**Comment by mmkulikov** [comment]
> В чистом yii-app-basic четыре yii файла :)

composer.json может?

**Comment by piliugin** [comment]
> composer.json может?

composer.json может быть еще и в разных других директориях, не только в корне yii-проекта

**Comment by nvlad** [comment]
> Так у сторма же индекс есть. Или он никак не поможет? Никак не воспользоваться его "родным" поиском? Ведь он довольно шустро ищет в проекте файл по Ctrl+Shift+N
он умеет только по имени файла, по маске не умеет

> composer.json может?
тогда 68 файлов :)

**Comment by mmkulikov** [comment]
> он умеет только по имени файла, по маске не умеет

Так маска и не нужна. Надо по полному имени файла.

**Comment by piliugin** [comment]
Возврат к версии [0.7.35.2](https://plugins.jetbrains.com/plugin/9388-yii2-support/update/41818) для меня решил проблему с переходами к файлам view.

**Comment by nvlad** [comment]
> Так маска и не нужна. Надо по полному имени файла.

@mmkulikov результаты поиска не дают точной картины расположения корня Yii, как и текущая реализация поиска.

@piliugin да, в той версии работа с view была реализована по другому. В вашем случае может быть её хватит, но из наиболее популярных проблем: нет поддержки вложенных папок с видами, нет поддержки тем.

**Comment by nvlad** [comment]
В новой версии добавил настройку для указания корневой папки Yii. Качайте, тестируйте :)

**Comment by mmkulikov** [comment]
> В новой версии добавил настройку для указания корневой папки Yii. 

Не нахожу её. ( И судя по всему из-за этого опять все вьюхи "красные"

**Comment by mmkulikov** [comment]
![2018-03-16_10-52-51](https://user-images.githubusercontent.com/4347816/37511624-36874596-2908-11e8-8152-7f27b4e5f22f.png)
Нашел. Может кому-то тоже поможет :)
