### ISSUE TITLE
all views missing since last update

### ISSUE THREAD

**Issue by cornernote** [nvlad/yii2support#169]
### What steps will reproduce the problem?

in controller:

```
return $this->render('index')
```
in view:

```
echo $this->render('test');
```

### What is the expected result?

Finding a view template.

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2007.3.1
| Plugin version   | 0.8.38.1

**Comment by nvlad** [comment]
Yii project root is PhpStorm project root?

**Comment by cornernote** [comment]
I don't think so, I always do Open Folder when I add a new project.

**Comment by nvlad** [comment]
how located yii root in phpstorm project?

yii root coincides phpstorm project root
![image](https://user-images.githubusercontent.com/2493052/37459051-00a37f54-2858-11e8-85a5-87c8236059e5.png)

yii root locate in nested directory
![image](https://user-images.githubusercontent.com/2493052/37459467-382cbd2c-2859-11e8-9de3-a53b8391cbf7.png)

**Comment by cornernote** [comment]
Ahh, I see.  Yes Yii is in the root, and the views are in `/src/views/`

![image](https://user-images.githubusercontent.com/51875/37479531-ca623dfc-28cc-11e8-967a-a1af61e88807.png)

**Comment by nvlad** [comment]
Released new plugin version with configurable Yii root folder.

**Comment by cornernote** [comment]
I upgraded the plugin... It's still not working.  Do I have to do something else?

**Comment by cornernote** [comment]
Ahh, I see the setting now.  I tried entering the following:

- `src`
- `/web/afi/console`
- `/web/afi/console/src`

None worked.

Any suggestions?

**Comment by cornernote** [comment]
the error message is:

> View file for "index" not found.

Would you be able to change it to:

> View file for "index" not found in /the/place/we/looked.

That would help me to understand what to put in the setting field.

**Comment by nvlad** [comment]
Check the latest(0.8.42.3) plugin version.

> Would you be able to change it to:
> > View file for "index" not found in /the/place/we/looked.

Thanx for idea. Added in release.

**Comment by cornernote** [comment]
The settings I put `src`:

![image](https://user-images.githubusercontent.com/51875/37552861-d3d2387e-2a0c-11e8-848a-71fef5513883.png)

But it still doesn't seem to find the views:

![image](https://user-images.githubusercontent.com/51875/37552849-b4ee44c0-2a0c-11e8-8bb9-81a87fd43d25.png)

**Comment by nvlad** [comment]
Please test this build. (Plugin file in attached archive)

[yii2support.zip](https://github.com/nvlad/yii2support/files/1829305/yii2support.zip)

**Comment by cornernote** [comment]
sorry for the delay, yes this works!

**Comment by AndriySvirin** [comment]
This works for me too.
