### ISSUE TITLE
Plugin settings

### ISSUE THREAD

**Issue by mmkulikov** [nvlad/yii2support#171]
![2018-03-16_16-15-09](https://user-images.githubusercontent.com/4347816/37525483-a7af3ef4-2935-11e8-806b-b6cc824373e9.png)
### What steps will reproduce the problem?
Открыть настройки плагина

### What is the expected result?
На последней версии 0.8.42 На ранних не проверял

### Additional info

![2018-03-16_16-15-09](https://user-images.githubusercontent.com/4347816/37525499-b3a6d26c-2935-11e8-8f7b-8c485b56c522.png)

**Comment by mmkulikov** [comment]
И попутно. Описание есть как это настраивать? Из того что есть так и не понял как этим пользоваться

**Comment by nvlad** [comment]
Спасибо за информацию.

> И попутно. Описание есть как это настраивать? Из того что есть так и не понял как этим пользоваться

Вы использовали темизацию в Yii?

**Comment by mmkulikov** [comment]
Нет. Не использовал

**Comment by nvlad** [comment]
Этот блок настроек предназначен для настройки путей к темам, по-умолчанию там стоят "значения из документации". После ознакомления с [разделом темизации в документации к фреймворку](https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/output-theming.md) думаю станет понятно, что там за значения и что можно настроить, хотя для большинства приложений это не нужно :)

**Comment by mmkulikov** [comment]
О темах я понимаю. Я думал это можно как-то применить для шаблонов писем... )
И ещё. Нашел опять проблему с вьюхами. Не переходит к вьюхе если она рендерится внутри другой вьюхи да ещё и из подпапки... :)

**Comment by nvlad** [comment]
Для писем не поможет, так как шаблоны писем не индексируются.

По поводу вьюх - опишите расположение файлов (скрин структуры проектов или что-нибудь подобное)

В тестовом проекте переходы работают нормально:
![image](https://user-images.githubusercontent.com/2493052/37707409-0e241272-2d14-11e8-929b-982ab474c785.png)

**Comment by mmkulikov** [comment]
Последняя версия уже переходит нормально.

**Comment by AndriySvirin** [comment]
Ne perehodit. Pitaetsya sozdat' fail poverh sushestvyeshego.

**Comment by nvlad** [comment]
Добрый день, к сожалению на данный момент плагин не поддерживает алиасы, а у вас в некоторых местах есть алиас common...

так что те виджеты что расположены в папке common плагин не увидит, а вот для тех что расположены в папке frontend надо заменить настройки на:
`@app/themes/*/modules/*` замените на `@app/themes/*/modules` и значение на `@app/modules`
`@app/themes/widgets/*` замените на `@app/themes/*/widgets` и значение на `@app/widgets`

по поводу поддержки алиасов, надеюсь в ближайшее время доберусь...

**Comment by buchenko** [comment]
дело в том, что модули и соответственно их контроллеры как раз и находятся в common/modules/ а в папке frontend/themes/basic/modules/ их вьюхи.
я так понгимаю, то пока не сделаете поддержку алиасов то мне оно пока не светит :(
