### ISSUE TITLE
Index Yii2Support.ViewFileIndex deserialization violates equals / hashCode contract for Value parameter

### ISSUE THREAD

**Issue by blacksmoke26** [nvlad/yii2support#178]
### What steps will reproduce the problem?
Randomly generates the following error:
Index Yii2Support.ViewFileIndex deserialization violates equals / hashCode contract for Value parameter

### What is the expected result?
N/A

### What do you get instead?
Big performance drop. PHPStorm CPU usage 60%+ / RAM usage about 5GB+.

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm 2018.1 EAP
| IDE Version      |  #PS-181.4203.107
| Plugin version   | 0.8.45.5
| Yii App Template | advanced

**Comment by nvlad** [comment]
Thanx for reporting. 

> Randomly generates the following error:
> Index Yii2Support.ViewFileIndex deserialization violates equals / hashCode contract for Value 

Until don`t know of error appear, we are work on fix it.

> PHPStorm CPU usage 60%+

For minimalize of CPU usage you have to disable "Missed PhpDoc variable declaration" inspection.
