### ISSUE TITLE
View in themes

### ISSUE THREAD

**Issue by muratymt** [nvlad/yii2support#18]
Are there settings to specify the path to the views in the themes?

**Comment by samdark** [comment]
Not that I'm aware of. What's your use case?

**Comment by a761208** [comment]
config/web.php
```php
        'view' => [
            'theme' => [
                'basePath' => '@app/themes/basic',
                'baseUrl' => '@web',
                'pathMap' => [
                    '@app/views' => '@app/themes/basic',
                    '@app/modules' => '@app/themes/basic/modules',
                    '@app/widgets' => '@app/themes/basic/widgets',
                ],
            ],
        ],
```
view file for "***" not found.

**Comment by insperedia** [comment]
This problem regards dynamic nature of Yii config. 
We can not read it from plugin in all cases (when there are conditionals or computed values).
Currently I gravitate to Yii component which will write cached version of config when app is running in debug mode. So plugin can securly read acached configs and get all needed information about applications: alliases, params, additional components to make autocomplete on Yii::$app->|, theme and so on.
@samdark have you any suggestions?

**Comment by samdark** [comment]
That's interesting idea. There are several options to do that including actually running the config file.

Each bootstrap script contains application instantiation of the app and usually `->run()`. App constructor accepts an array which is already evaluated config. So plugin can find the line where app instance is created, get the name of the variable holding the config from its constructor, create a separate file with `new Application($config)->run()` is replaced with `return $config`, execute it and write contents somewhere.

**Comment by blacksmoke26** [comment]
what about JSON config or plugin options in PHPStorm? We can hard code the theme path!

**Comment by insperedia** [comment]
1. It is not about themes only. Plugin needs lot of info from config.
2. Plugin should be configuration free or close to that.
