### ISSUE TITLE
Plugin doesn't offer create phpdoc for view

### ISSUE THREAD

**Issue by fjqtp** [nvlad/yii2support#184]
In penultimate version (not sure what version exactly) of the plugin I noticed very useful feature, it offered automatically create phpdoc in the beginning of view files with variables declaring. This happened every time I opened any view file.
In the latest version this doesn't persist. I wonder if this feature was removed intentionally or just broken now?

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2018.1.1
| Plugin version   | 0.8.42.6
| Yii App Template | advanced

**Comment by nvlad** [comment]
This function [have a problem with CPU usage](/nvlad/yii2support/issues/170). in latest plugin version this function/inspection disabled by default. Switch on "Missed PhpDoc variable declaration" inspection for enable this feature.
