### ISSUE TITLE
No way to turn off warnings about exceptions in views.

### ISSUE THREAD

**Issue by awesomeguy3** [nvlad/yii2support#187]
### What steps will reproduce the problem?
Using almost any Yii2 plugin inside views.

### What is the expected result?
No yellow background.

### What do you get instead?
Yellow background.

### Additional info
It would be nice to either have a feature to turn on/off warnings about unhandled exceptions in views as there are a lot of them, and I don't like to see so much yellow background all the time. There is no way to declare @throws like we can do it in PHPDoc.

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | latest
| Plugin version   | latest
| Yii App Template | advanced

**Comment by mike-kramer** [comment]
These warnings are not from this plugin, these warnings are produced by PhpStorm

**Comment by awesomeguy3** [comment]
Okay, I understand that, but was wondering if there is a way for this plugin to control that?

**Comment by nvlad** [comment]
Configure [scope](https://www.jetbrains.com/help/phpstorm/settings-scopes.html) excluded view files and assign this scope for "Unhandled exceptions" inspection and disable highlight for other. 

This trouble resolving with IDE and at this time not interested for plugin developers.
