### ISSUE TITLE
No autocomplete for user identity property

### ISSUE THREAD

**Issue by awesomeguy3** [nvlad/yii2support#188]
### What steps will reproduce the problem?
Typing Yii::$app->user->identity doesn't provide autocomplete from declared class.

### What is the expected result?
Autocomplete after I type Yii::$app->user->identity->{any char} with declared identity class in config.

### What do you get instead?
Nothing.

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | latest
| Plugin version   | latest
| Yii App Template | advanced

**Comment by insperedia** [comment]
Unfortunately right now plugin does not read settings, and I am not sure if it is possible to implement correctly. Officially recommended way to do that is to create Application class copy, and tune auto completion there.

**Comment by awesomeguy3** [comment]
Well, I believe there is a way to implement it. It would be very usefful feature.

**Comment by nvlad** [comment]
This task may be resolved without this plugin, see manual https://github.com/samdark/yii2-cookbook/blob/master/book/ide-autocompletion.md. 

Tasks resolving with another methods have a lowest priority for us.
