### ISSUE TITLE
Support for navigation with Yii-specific phpdoc

### ISSUE THREAD

**Issue by samdark** [nvlad/yii2support#21]
Yii has its own documentation tool which supports extended phpdoc for cross-referencing classes and methods. Would be great to add navigation for these. Here's description: https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md#markdown

**Comment by insperedia** [comment]
I checked  how we can implement this feature. To make it correct we need to implement lexer, and somehow connect it to PhpParser. But after analisys of how it already done in intellij i would suggest to use some kind of annotation. It could be custom annotation but looks like @see annotation can be used.
Have you considered to migrate to standard @see annotation tag?

**Comment by samdark** [comment]
We're using `@see` and it's quite different because it should be in a single line and with a link. Yii references are to concrete classes within description.

**Comment by insperedia** [comment]
@see allows to use concrete classes and fields. @see \yii\data\Model:rules()|description is complitely valid and works in PhpStorm

**Comment by samdark** [comment]
Sure. The thing is about our usage i.e. "You can execute [[yii\base\Component::canSetProperty|canSetProperty()]] to check..." would produce "You can execute `[canSetProperty]()`" in generated docs.

**Comment by insperedia** [comment]
Class name obviously should not be on one line. Description format is up to yii markdown parser. It could be in quotes, like string literals or double brackets. More over this change does not look to complecated. Regex + update Yii Documentator. I could do it my self. Fuctional test could be done without effort. Just by comparing generation results byte to byte. Myself  usually use framework code as documentation. And i think @see much more readable then double brakets and reader do not need to now what class he is in(yii use field name only whenever it possible). It happens often too me when i miss name of class I read.

**Comment by insperedia** [comment]
Change: Class name obviously should be on one line.

**Comment by insperedia** [comment]
Currently it does look to complicated for us.
