### ISSUE TITLE
Как создать view файл с помощью плагина?

### ISSUE THREAD

**Issue by sokollondon** [nvlad/yii2support#211]
### What steps will reproduce the problem?
Есть код `return $this->render('test');` 
Что нужно нажать, чтобы плагин создал view файл `test.php`?
При нажатии на лампочку (IDE Intention) нет пунктов для создания.
![2018-09-24_10-15-15](https://user-images.githubusercontent.com/11624566/45938489-e0839000-bfe3-11e8-91ff-322fc4dccbf6.png)

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2018.2.3
| Plugin version   | 0.10.56.18
| Yii App Template | basic

**Comment by nvlad** [comment]
Плагин предлагает создать файл в том случае, если такого файла не существует. Видимо по одному из путей (основная папка с view или в папке с темами уже есть подходящий файл)

**Comment by sokollondon** [comment]
У меня была проблема в настройках Inspections. Сбросил настройки по-умолчанию, плагин заработал =)
Настройки сбрасываются тут: Settings | Editor | Inspections -- Profile -- Restore Defaults
