### ISSUE TITLE
Ошибка для phpdoc

### ISSUE THREAD

**Issue by slo-nik** [nvlad/yii2support#215]
### What steps will reproduce the problem?
После копирования готовой модели в приложение получил ошибку для блока phpdoc.
"Property is unused in class app\modules\recipe\models\Recipe".
Если отключить плагин - ошибка "уходит".
![image](http://www.imageup.ru/img19/3210605/snimok-ehkrana-ot-2018-11-10-22-45-35.png)
### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 208.1.4
| Plugin version   |  0.10.56.18
| Yii App Template | basic

**Comment by nvlad** [comment]
Приветствую, попробуйте обновить схему БД в Databases, может она по каким-то причинам не обновилась

**Comment by insperedia** [comment]
Это не ошибка, так и должно работать. У вас не была добавленно соеденение к базе, но не синхронизировано.
