### ISSUE TITLE
Missing 1 property that corresponds to a database column

### ISSUE THREAD

**Issue by KnightYoshi** [nvlad/yii2support#224]
How does the plugin determine the columns? I have a field in my db that I've since renamed and changed the property in the PHPDoc comment, but it has a warning about the property that was renamed in the DB that it's missing.

**Comment by eLFuvo** [comment]
I have same issue for newly created models.

> PHPStorm 2018.1
> Yii2 Support Version: 0.10.57.23

**Comment by insperedia** [comment]
I guess you need to press reload in Database navigator. The plugin reads the information provided by IDE, not actual database

**Comment by KnightYoshi** [comment]
Yep! That was the the issue. Thanks for that. I don't use PhpStorm's built in database tools, I use other DB tools, so I wasn't aware of that.
