### ISSUE TITLE
type resulution for method one not work in the ActiveRecord itself when overwrite find.

### ISSUE THREAD

**Issue by feistiny** [nvlad/yii2support#230]
### What steps will reproduce the problem?
```php
class User extends ActiveRecord {
  public static function find() {
     return new UserQuery(get_called_class());
  }
  public function test(){
     $user = User::find()->one();
     $user->doSth();
  }
  public function doSth(){
     
  }
}
```

### What is the expected result?
autocomplete the doSth method.

### What do you get instead?
doSth not autocomplete 

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2019.1.2
| Plugin version   | v0.10.57.23
| Yii App Template | advanced

**Comment by feistiny** [comment]
In other ActiveRecord, the complete is ok.

**Comment by feistiny** [comment]
Surely I can add phpdoc 
`/** @var User $user*/` , but is this a bug?

**Comment by malsatin** [comment]
It is not about this plugin, but about phpDocs of yii2. You also need to check, if `$user` is null
