### ISSUE TITLE
PhpStorm 2019.3 freezes when class autocomplete on ubuntu

### ISSUE THREAD

**Issue by RuSPanzer** [nvlad/yii2support#237]
### What steps will reproduce the problem?
create new php file. write 
```
$a  = [
    'class' => 
]
```

### What is the expected result?
shown popup with class autocomplete

### What do you get instead?
phpstorm freeze and close him may only with kill 

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | PhpStorm 2019.3, Build #PS-193.5233.101, built on November 28, 2019
| Plugin version   | 0.10.57.23
| Yii App Template | basic

**Comment by alligator77** [comment]
on windows too

**Comment by Jooseph** [comment]
on macOS, yii2support is not work in PhpStorm 2019.3

**Comment by paulvales** [comment]
Кто в java шарит? гляньте че там)

**Comment by kialex** [comment]
Have the same problem

**Comment by Mikk36** [comment]
https://youtrack.jetbrains.com/issue/WI-50149

**Comment by nvlad** [comment]
Hi! I publish test version with the bug fix, please test it - https://github.com/nvlad/yii2support/issues/239#issuecomment-563465859

**Comment by nvlad** [comment]
Hi!
Released plugin version 0.10.57.33 with fix freezing IDE.
