### ISSUE TITLE
Plugin is incompatible with PhpStorm 2019.3

### ISSUE THREAD

**Issue by MaXal** [nvlad/yii2support#239]
We've marked your plugin as incompatible with PhpStorm 2019.3 due to the freezes that it causes:
#233 
#236 
#237 

As well as:
https://youtrack.jetbrains.com/issue/WI-50149
https://youtrack.jetbrains.com/issue/WI-48980
https://youtrack.jetbrains.com/issue/WI-50190
https://youtrack.jetbrains.com/issue/WI-50189

Feel free to contact us in any way if you need help to resolve the problem.

**Comment by sheershoff** [comment]
To all those who experience freezes.

I guess the best way to speed up fixing the freezes is to donate. While it may provoke a positive loop on bugs, I hope it won't. Just saying. Up to you, people.

**Comment by nvlad** [comment]
Hi!
Sorry, now few free time for the plugin support.
Test this version on freezes and another troubles [yii2support-0.10.57.24.jar.zip](https://github.com/nvlad/yii2support/files/3941957/yii2support-0.10.57.24.jar.zip)
Installation instructions read here https://github.com/nvlad/yii2support#installation

**Comment by Mikk36** [comment]
Works for me

**Comment by nvlad** [comment]
> Works for me
> 
> Edit: view links don't work in controller render() method (view name is not clickable).
> Also, it doesn't validate the supplied arguments for the view.

It works for me. Please use "Invalidate cache & restart..." for reindex the project

**Comment by Mikk36** [comment]
Thanks, everything seems to be working now.

**Comment by Beittil** [comment]
Seems to work again, tnx :)

Clicking on view links is also fine here.

**Comment by paulvales** [comment]
Thanks, it work

**Comment by kialex** [comment]
Good Job! Works for me!

**Comment by zhukovra** [comment]
Thank you. Fix works!

**Comment by papppeter** [comment]
HI,

can you push it to the repository as well? we have small adjustments on the plugin, which now are lost. 

thanks for your quick reaction.

**Comment by nvlad** [comment]
> HI,
> 
> can you push it to the repository as well? we have small adjustments on the plugin, which now are lost.
> 
> thanks for your quick reaction.

Hi!
Changes pushed. May be your send PR with changes and we add them to plugin?

**Comment by albertborsos** [comment]
Hi!

Will you release the fix? I cannot install the zip file mentioned above, because phpstorm says it is corrupted.

Thanks

**Comment by lshaf** [comment]
It's work like a charm.
Btw are you not going update that version to [here](https://plugins.jetbrains.com/plugin/9388-yii2-support) ?

**Comment by achetibi** [comment]
Hi,
Please test this version, i fixed the compatibility with PhpStorm 2019.3 and 2020 [yii2support-0.10.57.30.jar.zip](https://github.com/nvlad/yii2support/files/5452029/yii2support-0.10.57.30.jar.zip)

**Comment by cebe** [comment]
@achetibi nice, do you have a repo with the code?

**Comment by achetibi** [comment]
> @achetibi nice, do you have a repo with the code?

Yes, you can find it here [https://github.com/achetibi/yii2support](https://github.com/achetibi/yii2support)

**Comment by nvlad** [comment]
> Hi,
> Please test this version, i fixed the compatibility with PhpStorm 2019.3 and 2020 [yii2support-0.10.57.30.jar.zip](https://github.com/nvlad/yii2support/files/5452029/yii2support-0.10.57.30.jar.zip)

Hi! This build file not contain all components of plugin. Possible crashes.

A version will be released soon with updates from @achetibi and resolved code completion issues in the latest versions of the IDE.

**Comment by nvlad** [comment]
Hi!
Released plugin version 0.10.57.33.
