### ISSUE TITLE
IDE hanging while filling class in config

### ISSUE THREAD

**Issue by BetsuNo** [nvlad/yii2support#240]
### What steps will reproduce the problem?
In any Yii2 config file on attempt to fill 'class' value as MyClass::class (not as string) when the class suggestion popup shows.

### What is the expected result?
Something like ```'class' => MyClass::class,```

### What do you get instead?
IDE hangs and all unsaved data disappear

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2019.3
| Plugin version   | 0.10.57.23
| Yii App Template | any

In any othe context I have no problems with the class suggestions. Also there is no problem when plugin is disabled.

**Comment by slo-nik** [comment]
Такая же проблема.
При попытке написать имя класса как 
`'class' => NameClass::class`
PHPStorm зависает намертво, убить можно только через консоль.

**Comment by gergerichii** [comment]
Подтверждаю
![image](https://user-images.githubusercontent.com/5381312/72123600-d15c5900-3372-11ea-92fb-d2806895ff93.png)
Тут, при наборе буквы "Е" после "=>" тоже вис намертво. Пришлось отключить плагин чтобы продолжить.

**Comment by slo-nik** [comment]
> Подтверждаю
> ![image](https://user-images.githubusercontent.com/5381312/72123600-d15c5900-3372-11ea-92fb-d2806895ff93.png)
> Тут, при наборе буквы "Е" после "=>" тоже вис намертво. Пришлось отключить плагин чтобы продолжить.

Решение тут https://github.com/nvlad/yii2support/issues/239#issuecomment-563465859

**Comment by DBX12** [comment]
The solution is to install the Test version yii2support-0.10.57.24. The download link is in the issue referenced by slo-nik.
(this comment is mainly here for those who do not understand Russian and don't want to translate the half issue.)

**Comment by BetsuNo** [comment]
As @slo-nik mentioned above, solution is [here](https://github.com/nvlad/yii2support/issues/239#issuecomment-563465859)
