### ISSUE TITLE
Url autocomplete

### ISSUE THREAD

**Issue by siggi-k** [nvlad/yii2support#243]
### What steps will reproduce the problem?

**TransactionActualController**

public function _actionCreateTransactionActual_ ()
{...}

**View**

> now create Url::to([create-transaction-actual])
> you type :

Url::to([create..

### What is the expected result?

Url::to([create-transaction-actual])

### What do you get instead?

Url::to([create-trans-actual])

> Because there is a simple replacement of "action", regardless of whether it is at the beginning of the name or in the middle or at the end

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 
| Plugin version   | 
| Yii App Template | basic / advanced

**Comment by nvlad** [comment]
Hi!
Released plugin version 0.10.57.33.
Try for reproduce the problem.

**Comment by cebe** [comment]
Issue is still valid:

![Bildschirmfoto von »2020-11-03 13-10-15«](https://user-images.githubusercontent.com/189796/97983692-fb857880-1dd5-11eb-857e-82869d1ad5ea.png)

**Comment by cebe** [comment]
As far as I see this line should only replace "action" when it is at the beginning of the string:

https://github.com/nvlad/yii2support/blob/36e96d605255c4060d77c7ffde31be6cdefaa561/src/com/nvlad/yii2support/common/UrlUtils.java#L53

**Comment by cebe** [comment]
should be fixed by https://github.com/nvlad/yii2support/pull/257
