### ISSUE TITLE
Incorrect work in phpstorm 2020.2.2

### ISSUE THREAD

**Issue by NanakiRus** [nvlad/yii2support#252]
### What steps will reproduce the problem?
install plugin an try work

### What is the expected result?
phpstorm dont see diffs in realtime (you will see mistakes for everything)

### What do you get instead?
you will see mistakes for everything

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      |  2020.2.2
| Plugin version   | 0.10.57.23
| Yii App Template | basic / advanced

**Comment by zl939144892** [comment]
@nvlad Can fix this issue? Pls...

**Comment by nvlad** [comment]
Hi!
Released plugin version 0.10.57.33. With compatibility and frizzes fix.
