### ISSUE TITLE
Crash on PHPStorm 2020.2.2

### ISSUE THREAD

**Issue by cebe** [nvlad/yii2support#253]
### What steps will reproduce the problem?

see https://youtrack.jetbrains.com/issue/WI-55849

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2020.2.2
| Plugin version   | 0.10.57.23

**Comment by nvlad** [comment]
Hi!
Released plugin version 0.10.57.33. With compatibility fix.
