### ISSUE TITLE
Add latest release to GitHub and update ChangeLog

### ISSUE THREAD

**Issue by machour** [nvlad/yii2support#258]
Hi @nvlad and thank you so much for the latest release that fixes the crashes I've been experiencing and led me to uninstall the plugin a while ago.

I discovered by complete luck today that a new version was released to PhpStorm Marketplace. I was watching the Releases tab in GitHub which did not change.

Could you maybe tag a new release here and update the CHANGELOG.md file to reflect latest changes ?

Thank you again <3

**Comment by nvlad** [comment]
Hi! Updated)
