### ISSUE TITLE
Views can't be resolved in the project with custom structure

### ISSUE THREAD

**Issue by clcagency** [nvlad/yii2support#261]
### What steps will reproduce the problem?
I have several fairly large projects with several subdomains. I use the Advanced app template with custom directories (not only frontend and backend as it is in the pure template). Each domain is placed in a separate folder (admin, site, mobile, api for example). 

### What is the expected result?
The view file name in the render function in Controller should be clickable, and the view file should be opened after the click. The suggestion for the view's name should work too.

### What do you get instead?
![image](https://user-images.githubusercontent.com/29466142/102354844-2873a080-3fbc-11eb-9299-20ff3ebf1a19.png)

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2020.3
| Plugin version   | 0.10.57.33
| Yii App Template | advanced with custom folders

**Comment by nvlad** [comment]
yii root (vendor folder and yii.bat, init.bat files) located at "backend" folder?

**Comment by clcagency** [comment]
> yii root (vendor folder and yii.bat, init.bat files) located at "backend" folder?

Yes.

**Comment by nvlad** [comment]
> > yii root (vendor folder and yii.bat, init.bat files) located at "backend" folder?
> 
> Yes.

You a configured yii root in settings?

See
File -> Settings...
Languages & Frameworks -> PHP -> Yii2 Support

**Comment by clcagency** [comment]
Oh, great, that helped. Thanks to you. You did a great job! And I'm sorry to bother you.
