### ISSUE TITLE
Find view very simple logic , when view file not found

### ISSUE THREAD

**Issue by awebc** [nvlad/yii2support#267]
### What steps will reproduce the problem?
Now, plugin only support to find view file like below folder:
root
 --app
   ------controllers
     -- ---SiteController.php
  ---------------views
    --------------------site
       --------------------------index.php
SiteController::actionIndex() can find the view file: app/views/site/index.php

But ,when some app folder like this:
root
 -- apps
   -- ---app
      ---------controllers
      ---------------views

Cant`t find the view file .
### What is the expected result?
Just find the views/xx.php at views folder , the same depth folder of controller folder

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2019.1
| Plugin version   | latest version
| Yii App Template |  advanced

**Comment by nvlad** [comment]
the views is searching at views folder located at same level with controller folder
![image](https://user-images.githubusercontent.com/2493052/110512006-e159ff00-8115-11eb-8567-0d477cabc561.png)

**Comment by iglooom** [comment]
> the views is searching at views folder located at same level with controller folder

Not exactly, it is more complicated actually and I don't fully understand what going on. But I've implemented workaround for this such problem in https://github.com/iglooom/yii2support/commit/f7dc999fb3bc572a0c510a7e56f8abeefc40a456 
Simply split path by '/views' or '/controllers' and in my cases it works well.
