### ISSUE TITLE
`@web` не обязательно ссылается на папку `web` 

### ISSUE THREAD

**Issue by WinterSilence** [nvlad/yii2support#274]
`@web` не обязательно ссылается на папку `web` 
https://github.com/nvlad/yii2support/blob/28fa94b7f8aadef5561823d35364bb9f3db83b2a/src/com/nvlad/yii2support/utils/Yii2SupportSettings.java#L86

`yii\web\Application`:
~~~php
Yii::setAlias('@webroot', dirname($request->getScriptFile()));
Yii::setAlias('@web', $request->getBaseUrl());
~~~

Я переместил файлы из `web` в `public` т.к. в `web` у меня `app\web` классы.

Определить `@web` можно по `@app/*/index.php`

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2021.1.1
| Plugin version   | 0.10.58.37
| Yii App Template | basic

**Comment by nvlad** [comment]
Пожалуй, но это не типичный сценарий использования фреймворка и вычислить эту папку при статическом анализе не так уж и просто. 

 > Определить @web можно по @app/*/index.php
1) `@app/*/index.php` может отсутствовать, так как копируется в нужное место на этапе инициации проекта (выполнение init после разворачивания проекта) из папки окружения (envireonment);
2) Может присутствовать несколько папок содержащих index.php даже на этом уровне, а с учётом вложенности это может быть вообще большой проблемой. 


PS: Судя по коду отсылка к папке `/web` содержащей публичные ресурсы нигде в проекте не используется, так что не должна создавать проблем в использовании плагина.

**Comment by WinterSilence** [comment]
@nvlad пользуясь случаем, а `Yii Root Path` это корень проекта или `vendor/yiisoft/yii2`?

**Comment by nvlad** [comment]
> @nvlad пользуясь случаем, а `Yii Root Path` это корень проекта или `vendor/yiisoft/yii2`?

Корень Yii проекта (где лежат папка vendor, файлы yii.bat, init.bat, composer.json и т.п.). Оказалось что довольно большое количество разработчиков в качестве root папки используют родительскую папку и рядом держат различные файлы относящиеся к проекту, но не являющиеся частью сайта.

**Comment by WinterSilence** [comment]
@nvlad  хорошо бы добавить пояснение или проверку, чтобы не было двусмысленности и вопросов.
