### ISSUE TITLE
'vcruntime140.dll' 14.0 is not compatible with this PHP build linked with 14.16

### ISSUE THREAD

**Issue by WinterSilence** [nvlad/yii2support#281]
### What steps will reproduce the problem?

![изображение](https://user-images.githubusercontent.com/3521094/133997516-1c5a143a-9540-4853-acfa-7002fd37e9aa.png)

no warnings when I'm run this command in CMD

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 2021.2.2
| Plugin version   | 0.10.58.*
| Yii App Template | advanced 
| OS | Windows 10 x64

**Comment by xstreamka** [comment]
This is how I solve this problem myself.
Need to replace the file:
`C:\Users\user\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-3\212.5712.51\jbr\bin\vcruntime140.dll`
from:
`C:\Windows\System32\vcruntime140.dll`
And everything works.

**Comment by WinterSilence** [comment]
@xstreamka and wait fail at next update

**Comment by xstreamka** [comment]
> and wait fail at next update

@WinterSilence 
Yes it is.
If phpstorm is updated, I update this file.
So far just like that.

**Comment by WinterSilence** [comment]
@xstreamka plugin can use external/system dll to ovoid this problem?

**Comment by xstreamka** [comment]
@WinterSilence 
You may need to contact the plugin author.
I just offered a solution to the problem, so that at least somehow it worked.

**Comment by WinterSilence** [comment]
@xstreamka solution that creates other problems is not solution :(

**Comment by WinterSilence** [comment]
**fixed in PHPStorm 2022.2**
