### ISSUE TITLE
Reading view files from controllers inside custom folders in controllers folder

### ISSUE THREAD

**Issue by awesomeguy3** [nvlad/yii2support#51]
So basically, in controllers folder I have some folders for grouping of controllers. 
Example: ~/controllers/test/TestController.php, it's views would be located in ~/views/test/test/ directory 

This plugin shows me error that it cannot find it, while in controllers that are in /controllers/ folder directly, it can.

**Comment by insperedia** [comment]
Ok, thanks. Will check.

**Comment by insperedia** [comment]
I created same situation and checked code. Subforlder should work. Please investigate the problem deeper and put additional info here.

**Comment by awesomeguy3** [comment]
[http://prntscr.com/envr11](url) Here's a screenshot that shows that it cannot find the view. And everything works normally for controllers that aren't in subfolders. View for the controller that is in a subfolder is in correspoding subfolder also, Yii2 works fine.

**Comment by insperedia** [comment]
Unfortunatly screenshot link shows 404. You can just copy paste image into comment box.
I tried same thing it worked. May be there is some additional condition which we need to find.

**Comment by awesomeguy3** [comment]
Just copy this link and paste it into browser's search bar http://prntscr.com/envr11 and it should open normally, github somehow doesn't redirect good (or I don't know how to insert a link properly here).
And this is a screenshot of view file location http://prntscr.com/enwc5e 

Sorry that I scratched over names of folders and other file names (had to).

**Comment by insperedia** [comment]
I used for test "basic app" project template, but the bug happens in  "advanced app" template

**Comment by awesomeguy3** [comment]
Yeah, I forgot to mention it's advanced template.

**Comment by insperedia** [comment]
No problem. I put this info here for @nvlad

**Comment by w3lifer** [comment]
For me it happens in Basic template:

![yii2-view-file-for-index-not-found](https://cloud.githubusercontent.com/assets/14075412/25251632/b8d33e86-2622-11e7-8387-0a21b5d19ec5.png)

It is clean Basic application.

**Comment by awesomeguy3** [comment]
Still not solved.

**Comment by insperedia** [comment]
Unfortunatly yes. "Views" code belongs to second developer who is not very active last time. Will try improve code after I ll fix everthing in my part.
