### ISSUE TITLE
unresolved view parameters/variable

### ISSUE THREAD

**Issue by the-liquid-metal** [nvlad/yii2support#58]
hello.

the plugin shows error, if i write statements like this:
`$viewParam = ['var1' => 1, 'var2' => 2];`
`$this->render('view-file', $viewParam);`

but this one is not:
`$this->render('view-file', ['var1' => 1, 'var2' => 2]);`

**Comment by nvlad** [comment]
Hi, thanx for report. 
In next version inspection for second parameter resolve only array construction or `compcat` function for other cases(varialbles, function or method calls), validation will not be performed.
