### ISSUE TITLE
request feature: detect orphan view files

### ISSUE THREAD

**Issue by the-liquid-metal** [nvlad/yii2support#59]
Hello.
I thing it would be great if this plugin can detect orphan view files, in order to clean up the code base.
Listed in a tool window maybe?! (like find/search result)

**Comment by samdark** [comment]
Would be handy. PhpStorm already allows you to do that with "Find usages" on particular view template but you have to do it one by one. It's not 100% accurate though.

**Comment by the-liquid-metal** [comment]
It is totally fail. My files are located at "vendor". PhpStorm informs that there is no usage found to any files.

**Comment by samdark** [comment]
Would you please tell how to reproduce the issue?

**Comment by the-liquid-metal** [comment]
most things are standard yii2 module, except the module location itself. 
module definition in config is 
`'modules' => [`
&nbsp;&nbsp;&nbsp;&nbsp;`...`
&nbsp;&nbsp;&nbsp;&nbsp;`'module1' => ['class' => 'vendor1\dir\subdir\Module'],`
&nbsp;&nbsp;&nbsp;&nbsp;`...`
`],`
As `advanced project template`.

controller location: `\\vendor\vendor1\dir\subdir\controllers`
view location: `\\vendor\vendor1\dir\subdir\views`
(as Windows path. `\\` means the root of app.)

controller classname: `MyController1Controller` with `vendor1\dir\subdir\controllers` namespace.
view call statement: `$this->render('view-name');`
view actual file: `vendor1\dir\subdir\views\my-controller1\view-name.php`

everything are work fine, except the IDE recognition for view files.

**Comment by insperedia** [comment]
We can not securly detect view files, at least at this stage. 
About files in vendor, usually this dir marked as library folder and not related to project it self, so IDE behaves differently on those files.
I close this bug as wontfix.
