### ISSUE TITLE
.twig views suport

### ISSUE THREAD

**Issue by Insolita** [nvlad/yii2support#6]
I use .twig as default view extension, so, in my controllers I write view name without extension, But with this plugin i get error notices about not existing Views, because plugin check existing only php files as I think. (When i write full view name with extension, the error not appears) So, i not expect twig support like as in symfony - is difficult work, but keep in mind, that  view extension may be not only .php, and also .twig or .tpl for smarty

**Comment by nvlad** [comment]
Thanks for reporting!

**Comment by nvlad** [comment]
Hi!

in new release twig files without extension not mark as missed, variables support twig & smarty in future releases planed
