### ISSUE TITLE
unresolved dinamic view file

### ISSUE THREAD

**Issue by the-liquid-metal** [nvlad/yii2support#60]
hello.

If i write statements like this:
`$viewFile = 'not-exist';`
`$this->render($viewFile);`
the plugin **fail** to detect the missing file.

**Comment by nvlad** [comment]
Hi!
plugin resolve only string parameter, when using variables, there are many situations which are resolved during script execution.

**Comment by insperedia** [comment]
But code can evaluate some cases.
For example
if ($something) 
  $view = "view1.php";
else $view = "view2.php";

In this case we are able to find misspeled filename. There could be some unrevealed diffculties to implement this, but calculate possible values of variable could be usefull for future features.

**Comment by insperedia** [comment]
We do not see possibility to implement this
