### ISSUE TITLE
MissedFieldInspection error for beahviors/events in config.

### ISSUE THREAD

**Issue by MKiselev** [nvlad/yii2support#61]
Прежде всего хочу выразить огромную благодарность за данный плагин, особенно фичи новые порадовали.

Баг заключается в том,что получаю ошибку MissedFieldInspection если обработчик события или поведение описываем через конфигурацию.
http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html#configuration-format

```php
[
    'on search' => function ($event) {
        Yii::info("Keyword searched: " . $event->keyword);
    },
    'as indexer' => [
        'class' => 'app\components\IndexerBehavior',
        // ... property init values ...
    ],
]
```

**Comment by insperedia** [comment]
Спасибо. Проблема исправлена и будет включена в ближайший релиз.

**Comment by MKiselev** [comment]
@insperedia оперативненько, благодарю!
