### ISSUE TITLE
filed with name object

### ISSUE THREAD

**Issue by Ezyt** [nvlad/yii2support#68]
Hello, I have a problem in ActiveRecord class.  My class has property 'object'. if i used $config in construct and put key 'object' there, i would have an error: "Field 'object' not exists in referenced class %className% ". For example 
![image](https://cloud.githubusercontent.com/assets/8953729/24408108/32dd3b4a-13e6-11e7-8150-3fd2ffbcec94.png)

**Comment by insperedia** [comment]
I tried to get same problem. The problemis not connected with name 'object'.
IDE does not update class definition from PhpDoc right away.
Please check when such error exists if IDE do code completion for class fields, e.g. $this->(here should be missing field).

**Comment by insperedia** [comment]
Please give you IDE version please.

**Comment by insperedia** [comment]
Put this screenshot for myself
![image](https://cloud.githubusercontent.com/assets/1706065/24413293/4e58fdba-13db-11e7-9ac6-f61b8e5c8b7a.png)

**Comment by Ezyt** [comment]
PhpStorm 2017.1
Build #PS-171.3780.104, built on March 21, 2017
JRE: 1.8.0_112-release-736-b13 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by insperedia** [comment]
Thanks.
This is known PhpStorm bug. 
https://youtrack.jetbrains.com/issue/WI-23988
Vote for this bug to make progress faster.
![image](https://cloud.githubusercontent.com/assets/1706065/24445817/9007ea06-146b-11e7-84ca-87755dc5ff8d.png)
