### ISSUE TITLE
PHP global variables in templates

### ISSUE THREAD

**Issue by insperedia** [nvlad/yii2support#7]
Get error marking if my template gets data directly from $_GET, $_POST, $_REQUEST and so on.

**Comment by Insolita** [comment]
but why you use direct access in templates? I think that errors displaing true in this case - it potential security risk

**Comment by nvlad** [comment]
@insperedia Thanks for reporting

@Insolita It`s really bad practice, but the behavior of the plugin is not correct. In future may be add superglobal variables direct access inspection
