### ISSUE TITLE
skip validate "as behavior" and "on event" in arrays

### ISSUE THREAD

**Issue by Insolita** [nvlad/yii2support#72]
Now config with defined behaviors and evets with "as/on" syntax higlighted as errors
![screen](http://dl4.joxi.net/drive/2017/03/30/0008/3019/551883/83/e0a5defd3b.jpg)

**Comment by nvlad** [comment]
what version of plugin you have installed?

**Comment by MKiselev** [comment]
Hi @Insolita thx 4 migrik ext.
Please update plugin, it was fixed in release 0.3.17.5

Duplicated of #61 #65

**Comment by Insolita** [comment]
oops, sorry, my phpstorm didn't notify me about the availability of the update
