### ISSUE TITLE
Переход в места использования/контроллер

### ISSUE THREAD

**Issue by MKiselev** [nvlad/yii2support#78]
Хотелось бы иметь переход по клику обратно в места объявления, как минимум соответствующий контроллер .

**Comment by nvlad** [comment]
По клику куда?

**Comment by MKiselev** [comment]
@nvlad а вот это не могу додумать... Было несколько идей:
1) Как в RubyMine сбоку прикрутить кнопочку (https://snag.gy/gXrcZa.jpg)
2) Как в шторме Params hints (https://i.stack.imgur.com/uT9le.png)
3) Генерить какой-то свой комментарий...

В принципе сейчас можно просто сделать `/* @var MyController */` и кликать по нему, но хотелось бы большего.

**Comment by nvlad** [comment]
Идея как в RubyMain интересная и плюс hotkey, должно быть хорошо, спасибо за идею, самому подобного функционала порой не хватает. Закинем в копилку)

с Params hints не понял идеи

**Comment by MKiselev** [comment]
3. VarDoc обычно в начале файла описывается, я имел в виду туда.

**Comment by nvlad** [comment]
Привет! Добрался до этого функционала, пока сделал переход к месту вызова по хоткею (по умолчанию Ctrl+Alt+R) можешь потестировать :)
[yii2support.zip](https://github.com/nvlad/yii2support/files/1781717/yii2support.zip)
