### ISSUE TITLE
Автодополнение свойств зависимости когда она задаётся через сеттер

### ISSUE THREAD

**Issue by MKiselev** [nvlad/yii2support#84]
В Yii2 зависимость можно внедрить передав конфигурацию класса в сеттер.
https://yiiframework.com.ua/ru/doc/guide/2/concept-di-container/#setter-and-property-injection

На данный момент плагин отлично дополняет конфигурацию класса, в идеале бы дополнять и случай когда зависимость передается через сеттер, ведь в Yii2 много на этом завязано...

Живой пример:
```php
$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
$dataProvider->setSort([
    'defaultOrder' => [
        'time' => SORT_DESC,
    ],
]);
```

`defaultSort` хотелось бы автокомплитом.

Спасибо!

**Comment by insperedia** [comment]
Спасибо. Сделаем со временем.

**Comment by insperedia** [comment]
Resolution was pushed in master
