### ISSUE TITLE
Field 'template' not exists in referenced class \Closure

### ISSUE THREAD

**Issue by padlyuck** [nvlad/yii2support#89]
`ActiveForm::begin(['fieldConfig' => ['template' => "{input}\n{error}"]])`
Field 'template' not exists in referenced class \Closure

**Comment by w3lifer** [comment]
And `labelOptions` also ...

Screenshot (it is default `login` view in the `yii2-app-basic`):

![Field 'labelOptions' not exists in referenced class \Closure](https://cloud.githubusercontent.com/assets/14075412/24632401/a8c49958-18cc-11e7-9f95-b1cdc449905b.png)

**Comment by insperedia** [comment]
Ok, Thanks. Will fix soon.

**Comment by insperedia** [comment]
This bug fixed and postponed to release.
