### ISSUE TITLE
Wrong "View file for '../lng-btn' not found" in "Render method inspection".

### ISSUE THREAD

**Issue by TrueXakeP** [nvlad/yii2support#9]
The file exist there.

![error](https://cloud.githubusercontent.com/assets/5345528/22399307/8494f8c8-e5a2-11e6-99c2-0df80976b917.png)

A yii-app-advanced template
PhpStorm 2017.1 EAP
Build #PS-171.2613.13, built on January 25, 2017
PhpStorm EAP User
Expiration date: February 24, 2017
JRE: 1.8.0_112-release-b671 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by nvlad** [comment]
Thanks for reporting!
