### ISSUE TITLE
Автодополнение в правилах

### ISSUE THREAD

**Issue by MKiselev** [nvlad/yii2support#92]
Когда находимся в массиве который возвращается из метода rules(желательно учитывать, `array_merge`, `ArrayHelper::merge`, `+`) у `yii\base\Model` или любого наследника то подхватывать стандартные валидаторы и дополнять из поля:
![](https://snag.gy/r9jzKT.jpg)

http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html

**Comment by insperedia** [comment]
Да, это функционал стоит следующий на  очереди. 
Как доделаем работу с базой данных, реализуем.
Спасибо.

**Comment by insperedia** [comment]
Можешь пояснить что значит?
**(желательно учитывать, array_merge, ArrayHelper::merge, +)**

**Comment by MKiselev** [comment]
@insperedia ну частенько бывает так, что некоторый класс наследует родительские правила и добавляет свои, например:

```php
public function rules() {
    return array_merge(parent::rules(), [
        [['field'], 'validator'],
    ]);
}
```

**Comment by insperedia** [comment]
Говоря "поля правил" ты имеешь ввиду property родительского класса и методы validate?

**Comment by MKiselev** [comment]
Ну да. Запутанно выразился.

Т.е. для примера:
```php
/**
 * @property integer $id
 * @property string $name
 */
class ModelBase extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
        ];
    }
}

/**
 * @property string $foo
 */
class ModelBase extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_merge(parent::rules(), [
            [['foo'], 'required'],
        ]);
    }
}
```

Я не знаю на сколько часто в практике у других именно мердж, а не переопределение правил родителя идет, так что не могу сказать, нужно ли так замарачивать.

Но вот дополнение первого элемента массива названиями полей `name`, `foo` и стандартных валидаторов `required`, `string` маст хев)

**Comment by insperedia** [comment]
Спасибо за столь подробное разьяснение.
Я только не понял как мердж влияет на code completion.
С последнем абзацем очевино, и все будет работать иенно так. Более того будут ещё учитывать методы и standalone custom validator classes.
 Но на мой взгляд наличие мерджа не влияет на автодополнение.

**Comment by insperedia** [comment]
Functionality has been implemeted. Scheduled for next release.

**Comment by insperedia** [comment]
Beta release: https://plugins.jetbrains.com/plugin/download?updateId=35899
