### ISSUE TITLE
Переход к классу указанном в phpDoc в стиле yii

### ISSUE THREAD

**Issue by MKiselev** [nvlad/yii2support#93]
Yii2 строит доку на основе phpDock, varDoc, для ссылок там используется формат [[ClassName/methodName()/propertyName/fieldName]].

Например:
https://github.com/yiisoft/yii2/blob/master/framework/data/BaseDataProvider.php#L20
https://github.com/yiisoft/yii2/blob/master/framework/data/BaseDataProvider.php#L268

Для упрощения навигации не плохо было бы делать переходы через альт + клик.

**Comment by insperedia** [comment]
Возможность реализации этой фичи рассматривалась. К сожалению PHPStorm строит DOM только для @attributes. То есть туда нельзя подцепить "link" (reference). Как сделать надстройку в PHP лексере не совсем ясно. Его код закрыт.

**Comment by insperedia** [comment]
Вижу ты активен в нашем репо. Нет желания потестить код перед релизом. Сейчас готово обновление для работы сбазой данных. При наличии Connection должен работать auto complete столбцов и таблиц. Так же есть снхронизация @propery с базой. И проверка и QuickFix для создания параметров запроса.

**Comment by MKiselev** [comment]
@insperedia конечно хочу)) Отписал на почту указанную в профиле.
