### ISSUE TITLE
Автодополнение компонентов, описанных в конфигурации приложения

### ISSUE THREAD

**Issue by MKiselev** [nvlad/yii2support#94]
![](http://image.prntscr.com/image/8d4b3e7323dc43ca8441761552d1cb8f.png)

Сейчас это делается подменой Yii.php файла и описанием phpDoc https://github.com/samdark/yii2-cookbook/blob/master/book/ide-autocompletion.md

**Comment by nvlad** [comment]
Сейчас мы нацелены на реализацию функционала, который нельзя получить другими способами (например подменой Yii.php). Так что надеяться на появление подобного функционала в ближайшее время особо не стоит.
