### ISSUE TITLE
Condition parameters must be defined

### ISSUE THREAD

**Issue by MKiselev** [nvlad/yii2support#95]
![](https://snag.gy/m75OER.jpg)

Когда задаю правую часть условия через именнованный плейсхолдер, то ругается.

Если убрать двоеточия, то всё нормально понимает.

Версия плагина 0.4.17.0

**Comment by MKiselev** [comment]
Хм... Но это не точно :)
Expression в where вообще неадекватно себя ведёт!

**Comment by insperedia** [comment]
Поправил. К сожалению в данной верии Expression не планируется поддерживать. Там конструктор, и у нас в основном методы. Решил не усложнаять, у там кучу тестировать.
