### ISSUE TITLE
Детектор Yii2

### ISSUE THREAD

**Issue by insperedia** [nvlad/yii2support#96]
Сделать детектор Yii2

**Comment by MKiselev** [comment]
@insperedia что за детектор?

**Comment by nvlad** [comment]
Определение используется ли Yii2 в проекте открытом в IDE, если нет, то отключать плагин

**Comment by insperedia** [comment]
@nvlad Вообще проблема возникает вроде пока в работе со view. Мне подчеркивает в Symfony. Там может просто сделать проверку на наследование. 
В остальном может только если производительность страдает. Можно сделать просто проверку на наличие Yii класса и делать проверку в начале.

**Comment by samdark** [comment]
Хорошая идея.

**Comment by samdark** [comment]
Вообще в PhpStorm есть "framework integration" и поддержка Yii 2 / Symfony с автодетектом. Возможно, удастся вытащить оттуда информацию или найти исходник детекта.

**Comment by nvlad** [comment]
Имеется ввиду плагин https://plugins.jetbrains.com/plugin/7143-framework-mvc-structure-support ? Попробую посмотреть, но вроде он поддерживает только Yii1 и его разработку и поддержку закрыли.

**Comment by insperedia** [comment]
Если мы всегда будем читать родителей классов то \та проблемаотпадает. Класс FrameworkDetector есть, но доков по нему нету и я пока не нашел плагина где он использовался бы. Проблема в модуле view исправили, это баг думаю надо закрыть.

**Comment by samdark** [comment]
Да, тот самый плагин.
